/* automatically generated by rust-bindgen */

pub const __BITS_PER_LONG: u32 = 64;
pub const __FD_SETSIZE: u32 = 1024;
pub const EM_NONE: u32 = 0;
pub const EM_M32: u32 = 1;
pub const EM_SPARC: u32 = 2;
pub const EM_386: u32 = 3;
pub const EM_68K: u32 = 4;
pub const EM_88K: u32 = 5;
pub const EM_486: u32 = 6;
pub const EM_860: u32 = 7;
pub const EM_MIPS: u32 = 8;
pub const EM_MIPS_RS3_LE: u32 = 10;
pub const EM_MIPS_RS4_BE: u32 = 10;
pub const EM_PARISC: u32 = 15;
pub const EM_SPARC32PLUS: u32 = 18;
pub const EM_PPC: u32 = 20;
pub const EM_PPC64: u32 = 21;
pub const EM_SPU: u32 = 23;
pub const EM_ARM: u32 = 40;
pub const EM_SH: u32 = 42;
pub const EM_SPARCV9: u32 = 43;
pub const EM_H8_300: u32 = 46;
pub const EM_IA_64: u32 = 50;
pub const EM_X86_64: u32 = 62;
pub const EM_S390: u32 = 22;
pub const EM_CRIS: u32 = 76;
pub const EM_M32R: u32 = 88;
pub const EM_MN10300: u32 = 89;
pub const EM_OPENRISC: u32 = 92;
pub const EM_BLACKFIN: u32 = 106;
pub const EM_ALTERA_NIOS2: u32 = 113;
pub const EM_TI_C6000: u32 = 140;
pub const EM_AARCH64: u32 = 183;
pub const EM_TILEPRO: u32 = 188;
pub const EM_MICROBLAZE: u32 = 189;
pub const EM_TILEGX: u32 = 191;
pub const EM_BPF: u32 = 247;
pub const EM_FRV: u32 = 21569;
pub const EM_ALPHA: u32 = 36902;
pub const EM_CYGNUS_M32R: u32 = 36929;
pub const EM_S390_OLD: u32 = 41872;
pub const EM_CYGNUS_MN10300: u32 = 48879;
pub const PT_NULL: u32 = 0;
pub const PT_LOAD: u32 = 1;
pub const PT_DYNAMIC: u32 = 2;
pub const PT_INTERP: u32 = 3;
pub const PT_NOTE: u32 = 4;
pub const PT_SHLIB: u32 = 5;
pub const PT_PHDR: u32 = 6;
pub const PT_TLS: u32 = 7;
pub const PT_LOOS: u32 = 1610612736;
pub const PT_HIOS: u32 = 1879048191;
pub const PT_LOPROC: u32 = 1879048192;
pub const PT_HIPROC: u32 = 2147483647;
pub const PT_GNU_EH_FRAME: u32 = 1685382480;
pub const PT_GNU_STACK: u32 = 1685382481;
pub const PN_XNUM: u32 = 65535;
pub const ET_NONE: u32 = 0;
pub const ET_REL: u32 = 1;
pub const ET_EXEC: u32 = 2;
pub const ET_DYN: u32 = 3;
pub const ET_CORE: u32 = 4;
pub const ET_LOPROC: u32 = 65280;
pub const ET_HIPROC: u32 = 65535;
pub const DT_NULL: u32 = 0;
pub const DT_NEEDED: u32 = 1;
pub const DT_PLTRELSZ: u32 = 2;
pub const DT_PLTGOT: u32 = 3;
pub const DT_HASH: u32 = 4;
pub const DT_STRTAB: u32 = 5;
pub const DT_SYMTAB: u32 = 6;
pub const DT_RELA: u32 = 7;
pub const DT_RELASZ: u32 = 8;
pub const DT_RELAENT: u32 = 9;
pub const DT_STRSZ: u32 = 10;
pub const DT_SYMENT: u32 = 11;
pub const DT_INIT: u32 = 12;
pub const DT_FINI: u32 = 13;
pub const DT_SONAME: u32 = 14;
pub const DT_RPATH: u32 = 15;
pub const DT_SYMBOLIC: u32 = 16;
pub const DT_REL: u32 = 17;
pub const DT_RELSZ: u32 = 18;
pub const DT_RELENT: u32 = 19;
pub const DT_PLTREL: u32 = 20;
pub const DT_DEBUG: u32 = 21;
pub const DT_TEXTREL: u32 = 22;
pub const DT_JMPREL: u32 = 23;
pub const DT_ENCODING: u32 = 32;
pub const OLD_DT_LOOS: u32 = 1610612736;
pub const DT_LOOS: u32 = 1610612749;
pub const DT_HIOS: u32 = 1879044096;
pub const DT_VALRNGLO: u32 = 1879047424;
pub const DT_VALRNGHI: u32 = 1879047679;
pub const DT_ADDRRNGLO: u32 = 1879047680;
pub const DT_ADDRRNGHI: u32 = 1879047935;
pub const DT_VERSYM: u32 = 1879048176;
pub const DT_RELACOUNT: u32 = 1879048185;
pub const DT_RELCOUNT: u32 = 1879048186;
pub const DT_FLAGS_1: u32 = 1879048187;
pub const DT_VERDEF: u32 = 1879048188;
pub const DT_VERDEFNUM: u32 = 1879048189;
pub const DT_VERNEED: u32 = 1879048190;
pub const DT_VERNEEDNUM: u32 = 1879048191;
pub const OLD_DT_HIOS: u32 = 1879048191;
pub const DT_LOPROC: u32 = 1879048192;
pub const DT_HIPROC: u32 = 2147483647;
pub const STB_LOCAL: u32 = 0;
pub const STB_GLOBAL: u32 = 1;
pub const STB_WEAK: u32 = 2;
pub const STT_NOTYPE: u32 = 0;
pub const STT_OBJECT: u32 = 1;
pub const STT_FUNC: u32 = 2;
pub const STT_SECTION: u32 = 3;
pub const STT_FILE: u32 = 4;
pub const STT_COMMON: u32 = 5;
pub const STT_TLS: u32 = 6;
pub const EI_NIDENT: u32 = 16;
pub const PF_R: u32 = 4;
pub const PF_W: u32 = 2;
pub const PF_X: u32 = 1;
pub const SHT_NULL: u32 = 0;
pub const SHT_PROGBITS: u32 = 1;
pub const SHT_SYMTAB: u32 = 2;
pub const SHT_STRTAB: u32 = 3;
pub const SHT_RELA: u32 = 4;
pub const SHT_HASH: u32 = 5;
pub const SHT_DYNAMIC: u32 = 6;
pub const SHT_NOTE: u32 = 7;
pub const SHT_NOBITS: u32 = 8;
pub const SHT_REL: u32 = 9;
pub const SHT_SHLIB: u32 = 10;
pub const SHT_DYNSYM: u32 = 11;
pub const SHT_NUM: u32 = 12;
pub const SHT_LOPROC: u32 = 1879048192;
pub const SHT_HIPROC: u32 = 2147483647;
pub const SHT_LOUSER: u32 = 2147483648;
pub const SHT_HIUSER: u32 = 4294967295;
pub const SHF_WRITE: u32 = 1;
pub const SHF_ALLOC: u32 = 2;
pub const SHF_EXECINSTR: u32 = 4;
pub const SHF_RELA_LIVEPATCH: u32 = 1048576;
pub const SHF_RO_AFTER_INIT: u32 = 2097152;
pub const SHF_MASKPROC: u32 = 4026531840;
pub const SHN_UNDEF: u32 = 0;
pub const SHN_LORESERVE: u32 = 65280;
pub const SHN_LOPROC: u32 = 65280;
pub const SHN_HIPROC: u32 = 65311;
pub const SHN_LIVEPATCH: u32 = 65312;
pub const SHN_ABS: u32 = 65521;
pub const SHN_COMMON: u32 = 65522;
pub const SHN_HIRESERVE: u32 = 65535;
pub const EI_MAG0: u32 = 0;
pub const EI_MAG1: u32 = 1;
pub const EI_MAG2: u32 = 2;
pub const EI_MAG3: u32 = 3;
pub const EI_CLASS: u32 = 4;
pub const EI_DATA: u32 = 5;
pub const EI_VERSION: u32 = 6;
pub const EI_OSABI: u32 = 7;
pub const EI_PAD: u32 = 8;
pub const ELFMAG0: u32 = 127;
pub const ELFMAG1: u8 = 69u8;
pub const ELFMAG2: u8 = 76u8;
pub const ELFMAG3: u8 = 70u8;
pub const ELFMAG: &'static [u8; 5usize] = b"\x7FELF\0";
pub const SELFMAG: u32 = 4;
pub const ELFCLASSNONE: u32 = 0;
pub const ELFCLASS32: u32 = 1;
pub const ELFCLASS64: u32 = 2;
pub const ELFCLASSNUM: u32 = 3;
pub const ELFDATANONE: u32 = 0;
pub const ELFDATA2LSB: u32 = 1;
pub const ELFDATA2MSB: u32 = 2;
pub const EV_NONE: u32 = 0;
pub const EV_CURRENT: u32 = 1;
pub const EV_NUM: u32 = 2;
pub const ELFOSABI_NONE: u32 = 0;
pub const ELFOSABI_LINUX: u32 = 3;
pub const ELF_OSABI: u32 = 0;
pub const NT_PRSTATUS: u32 = 1;
pub const NT_PRFPREG: u32 = 2;
pub const NT_PRPSINFO: u32 = 3;
pub const NT_TASKSTRUCT: u32 = 4;
pub const NT_AUXV: u32 = 6;
pub const NT_SIGINFO: u32 = 1397311305;
pub const NT_FILE: u32 = 1179208773;
pub const NT_PRXFPREG: u32 = 1189489535;
pub const NT_PPC_VMX: u32 = 256;
pub const NT_PPC_SPE: u32 = 257;
pub const NT_PPC_VSX: u32 = 258;
pub const NT_PPC_TAR: u32 = 259;
pub const NT_PPC_PPR: u32 = 260;
pub const NT_PPC_DSCR: u32 = 261;
pub const NT_PPC_EBB: u32 = 262;
pub const NT_PPC_PMU: u32 = 263;
pub const NT_PPC_TM_CGPR: u32 = 264;
pub const NT_PPC_TM_CFPR: u32 = 265;
pub const NT_PPC_TM_CVMX: u32 = 266;
pub const NT_PPC_TM_CVSX: u32 = 267;
pub const NT_PPC_TM_SPR: u32 = 268;
pub const NT_PPC_TM_CTAR: u32 = 269;
pub const NT_PPC_TM_CPPR: u32 = 270;
pub const NT_PPC_TM_CDSCR: u32 = 271;
pub const NT_386_TLS: u32 = 512;
pub const NT_386_IOPERM: u32 = 513;
pub const NT_X86_XSTATE: u32 = 514;
pub const NT_S390_HIGH_GPRS: u32 = 768;
pub const NT_S390_TIMER: u32 = 769;
pub const NT_S390_TODCMP: u32 = 770;
pub const NT_S390_TODPREG: u32 = 771;
pub const NT_S390_CTRS: u32 = 772;
pub const NT_S390_PREFIX: u32 = 773;
pub const NT_S390_LAST_BREAK: u32 = 774;
pub const NT_S390_SYSTEM_CALL: u32 = 775;
pub const NT_S390_TDB: u32 = 776;
pub const NT_S390_VXRS_LOW: u32 = 777;
pub const NT_S390_VXRS_HIGH: u32 = 778;
pub const NT_ARM_VFP: u32 = 1024;
pub const NT_ARM_TLS: u32 = 1025;
pub const NT_ARM_HW_BREAK: u32 = 1026;
pub const NT_ARM_HW_WATCH: u32 = 1027;
pub const NT_ARM_SYSTEM_CALL: u32 = 1028;
pub const NT_METAG_CBUF: u32 = 1280;
pub const NT_METAG_RPIPE: u32 = 1281;
pub const NT_METAG_TLS: u32 = 1282;
pub type __s8 = ::std::os::raw::c_schar;
pub type __u8 = ::std::os::raw::c_uchar;
pub type __s16 = ::std::os::raw::c_short;
pub type __u16 = ::std::os::raw::c_ushort;
pub type __s32 = ::std::os::raw::c_int;
pub type __u32 = ::std::os::raw::c_uint;
pub type __s64 = ::std::os::raw::c_longlong;
pub type __u64 = ::std::os::raw::c_ulonglong;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct __kernel_fd_set {
    pub fds_bits: [::std::os::raw::c_ulong; 16usize],
}
#[test]
fn bindgen_test_layout___kernel_fd_set() {
    assert_eq!(
        ::std::mem::size_of::<__kernel_fd_set>(),
        128usize,
        concat!("Size of: ", stringify!(__kernel_fd_set))
    );
    assert_eq!(
        ::std::mem::align_of::<__kernel_fd_set>(),
        8usize,
        concat!("Alignment of ", stringify!(__kernel_fd_set))
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<__kernel_fd_set>())).fds_bits as *const _ as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(__kernel_fd_set),
            "::",
            stringify!(fds_bits)
        )
    );
}
pub type __kernel_sighandler_t =
    ::std::option::Option<unsafe extern "C" fn(arg1: ::std::os::raw::c_int)>;
pub type __kernel_key_t = ::std::os::raw::c_int;
pub type __kernel_mqd_t = ::std::os::raw::c_int;
pub type __kernel_old_uid_t = ::std::os::raw::c_ushort;
pub type __kernel_old_gid_t = ::std::os::raw::c_ushort;
pub type __kernel_old_dev_t = ::std::os::raw::c_ulong;
pub type __kernel_long_t = ::std::os::raw::c_long;
pub type __kernel_ulong_t = ::std::os::raw::c_ulong;
pub type __kernel_ino_t = __kernel_ulong_t;
pub type __kernel_mode_t = ::std::os::raw::c_uint;
pub type __kernel_pid_t = ::std::os::raw::c_int;
pub type __kernel_ipc_pid_t = ::std::os::raw::c_int;
pub type __kernel_uid_t = ::std::os::raw::c_uint;
pub type __kernel_gid_t = ::std::os::raw::c_uint;
pub type __kernel_suseconds_t = __kernel_long_t;
pub type __kernel_daddr_t = ::std::os::raw::c_int;
pub type __kernel_uid32_t = ::std::os::raw::c_uint;
pub type __kernel_gid32_t = ::std::os::raw::c_uint;
pub type __kernel_size_t = __kernel_ulong_t;
pub type __kernel_ssize_t = __kernel_long_t;
pub type __kernel_ptrdiff_t = __kernel_long_t;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct __kernel_fsid_t {
    pub val: [::std::os::raw::c_int; 2usize],
}
#[test]
fn bindgen_test_layout___kernel_fsid_t() {
    assert_eq!(
        ::std::mem::size_of::<__kernel_fsid_t>(),
        8usize,
        concat!("Size of: ", stringify!(__kernel_fsid_t))
    );
    assert_eq!(
        ::std::mem::align_of::<__kernel_fsid_t>(),
        4usize,
        concat!("Alignment of ", stringify!(__kernel_fsid_t))
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<__kernel_fsid_t>())).val as *const _ as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(__kernel_fsid_t),
            "::",
            stringify!(val)
        )
    );
}
pub type __kernel_off_t = __kernel_long_t;
pub type __kernel_loff_t = ::std::os::raw::c_longlong;
pub type __kernel_time_t = __kernel_long_t;
pub type __kernel_clock_t = __kernel_long_t;
pub type __kernel_timer_t = ::std::os::raw::c_int;
pub type __kernel_clockid_t = ::std::os::raw::c_int;
pub type __kernel_caddr_t = *mut ::std::os::raw::c_char;
pub type __kernel_uid16_t = ::std::os::raw::c_ushort;
pub type __kernel_gid16_t = ::std::os::raw::c_ushort;
pub type __le16 = __u16;
pub type __be16 = __u16;
pub type __le32 = __u32;
pub type __be32 = __u32;
pub type __le64 = __u64;
pub type __be64 = __u64;
pub type __sum16 = __u16;
pub type __wsum = __u32;
pub type Elf32_Addr = __u32;
pub type Elf32_Half = __u16;
pub type Elf32_Off = __u32;
pub type Elf32_Sword = __s32;
pub type Elf32_Word = __u32;
pub type Elf64_Addr = __u64;
pub type Elf64_Half = __u16;
pub type Elf64_SHalf = __s16;
pub type Elf64_Off = __u64;
pub type Elf64_Sword = __s32;
pub type Elf64_Word = __u32;
pub type Elf64_Xword = __u64;
pub type Elf64_Sxword = __s64;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct dynamic {
    pub d_tag: Elf32_Sword,
    pub d_un: dynamic__bindgen_ty_1,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union dynamic__bindgen_ty_1 {
    pub d_val: Elf32_Sword,
    pub d_ptr: Elf32_Addr,
    _bindgen_union_align: u32,
}
#[test]
fn bindgen_test_layout_dynamic__bindgen_ty_1() {
    assert_eq!(
        ::std::mem::size_of::<dynamic__bindgen_ty_1>(),
        4usize,
        concat!("Size of: ", stringify!(dynamic__bindgen_ty_1))
    );
    assert_eq!(
        ::std::mem::align_of::<dynamic__bindgen_ty_1>(),
        4usize,
        concat!("Alignment of ", stringify!(dynamic__bindgen_ty_1))
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<dynamic__bindgen_ty_1>())).d_val as *const _ as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(dynamic__bindgen_ty_1),
            "::",
            stringify!(d_val)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<dynamic__bindgen_ty_1>())).d_ptr as *const _ as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(dynamic__bindgen_ty_1),
            "::",
            stringify!(d_ptr)
        )
    );
}
#[test]
fn bindgen_test_layout_dynamic() {
    assert_eq!(
        ::std::mem::size_of::<dynamic>(),
        8usize,
        concat!("Size of: ", stringify!(dynamic))
    );
    assert_eq!(
        ::std::mem::align_of::<dynamic>(),
        4usize,
        concat!("Alignment of ", stringify!(dynamic))
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<dynamic>())).d_tag as *const _ as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(dynamic),
            "::",
            stringify!(d_tag)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<dynamic>())).d_un as *const _ as usize },
        4usize,
        concat!(
            "Offset of field: ",
            stringify!(dynamic),
            "::",
            stringify!(d_un)
        )
    );
}
pub type Elf32_Dyn = dynamic;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct Elf64_Dyn {
    pub d_tag: Elf64_Sxword,
    pub d_un: Elf64_Dyn__bindgen_ty_1,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union Elf64_Dyn__bindgen_ty_1 {
    pub d_val: Elf64_Xword,
    pub d_ptr: Elf64_Addr,
    _bindgen_union_align: u64,
}
#[test]
fn bindgen_test_layout_Elf64_Dyn__bindgen_ty_1() {
    assert_eq!(
        ::std::mem::size_of::<Elf64_Dyn__bindgen_ty_1>(),
        8usize,
        concat!("Size of: ", stringify!(Elf64_Dyn__bindgen_ty_1))
    );
    assert_eq!(
        ::std::mem::align_of::<Elf64_Dyn__bindgen_ty_1>(),
        8usize,
        concat!("Alignment of ", stringify!(Elf64_Dyn__bindgen_ty_1))
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<Elf64_Dyn__bindgen_ty_1>())).d_val as *const _ as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(Elf64_Dyn__bindgen_ty_1),
            "::",
            stringify!(d_val)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<Elf64_Dyn__bindgen_ty_1>())).d_ptr as *const _ as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(Elf64_Dyn__bindgen_ty_1),
            "::",
            stringify!(d_ptr)
        )
    );
}
#[test]
fn bindgen_test_layout_Elf64_Dyn() {
    assert_eq!(
        ::std::mem::size_of::<Elf64_Dyn>(),
        16usize,
        concat!("Size of: ", stringify!(Elf64_Dyn))
    );
    assert_eq!(
        ::std::mem::align_of::<Elf64_Dyn>(),
        8usize,
        concat!("Alignment of ", stringify!(Elf64_Dyn))
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<Elf64_Dyn>())).d_tag as *const _ as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(Elf64_Dyn),
            "::",
            stringify!(d_tag)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<Elf64_Dyn>())).d_un as *const _ as usize },
        8usize,
        concat!(
            "Offset of field: ",
            stringify!(Elf64_Dyn),
            "::",
            stringify!(d_un)
        )
    );
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct elf32_rel {
    pub r_offset: Elf32_Addr,
    pub r_info: Elf32_Word,
}
#[test]
fn bindgen_test_layout_elf32_rel() {
    assert_eq!(
        ::std::mem::size_of::<elf32_rel>(),
        8usize,
        concat!("Size of: ", stringify!(elf32_rel))
    );
    assert_eq!(
        ::std::mem::align_of::<elf32_rel>(),
        4usize,
        concat!("Alignment of ", stringify!(elf32_rel))
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<elf32_rel>())).r_offset as *const _ as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(elf32_rel),
            "::",
            stringify!(r_offset)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<elf32_rel>())).r_info as *const _ as usize },
        4usize,
        concat!(
            "Offset of field: ",
            stringify!(elf32_rel),
            "::",
            stringify!(r_info)
        )
    );
}
pub type Elf32_Rel = elf32_rel;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct elf64_rel {
    pub r_offset: Elf64_Addr,
    pub r_info: Elf64_Xword,
}
#[test]
fn bindgen_test_layout_elf64_rel() {
    assert_eq!(
        ::std::mem::size_of::<elf64_rel>(),
        16usize,
        concat!("Size of: ", stringify!(elf64_rel))
    );
    assert_eq!(
        ::std::mem::align_of::<elf64_rel>(),
        8usize,
        concat!("Alignment of ", stringify!(elf64_rel))
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<elf64_rel>())).r_offset as *const _ as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(elf64_rel),
            "::",
            stringify!(r_offset)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<elf64_rel>())).r_info as *const _ as usize },
        8usize,
        concat!(
            "Offset of field: ",
            stringify!(elf64_rel),
            "::",
            stringify!(r_info)
        )
    );
}
pub type Elf64_Rel = elf64_rel;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct elf32_rela {
    pub r_offset: Elf32_Addr,
    pub r_info: Elf32_Word,
    pub r_addend: Elf32_Sword,
}
#[test]
fn bindgen_test_layout_elf32_rela() {
    assert_eq!(
        ::std::mem::size_of::<elf32_rela>(),
        12usize,
        concat!("Size of: ", stringify!(elf32_rela))
    );
    assert_eq!(
        ::std::mem::align_of::<elf32_rela>(),
        4usize,
        concat!("Alignment of ", stringify!(elf32_rela))
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<elf32_rela>())).r_offset as *const _ as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(elf32_rela),
            "::",
            stringify!(r_offset)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<elf32_rela>())).r_info as *const _ as usize },
        4usize,
        concat!(
            "Offset of field: ",
            stringify!(elf32_rela),
            "::",
            stringify!(r_info)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<elf32_rela>())).r_addend as *const _ as usize },
        8usize,
        concat!(
            "Offset of field: ",
            stringify!(elf32_rela),
            "::",
            stringify!(r_addend)
        )
    );
}
pub type Elf32_Rela = elf32_rela;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct elf64_rela {
    pub r_offset: Elf64_Addr,
    pub r_info: Elf64_Xword,
    pub r_addend: Elf64_Sxword,
}
#[test]
fn bindgen_test_layout_elf64_rela() {
    assert_eq!(
        ::std::mem::size_of::<elf64_rela>(),
        24usize,
        concat!("Size of: ", stringify!(elf64_rela))
    );
    assert_eq!(
        ::std::mem::align_of::<elf64_rela>(),
        8usize,
        concat!("Alignment of ", stringify!(elf64_rela))
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<elf64_rela>())).r_offset as *const _ as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(elf64_rela),
            "::",
            stringify!(r_offset)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<elf64_rela>())).r_info as *const _ as usize },
        8usize,
        concat!(
            "Offset of field: ",
            stringify!(elf64_rela),
            "::",
            stringify!(r_info)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<elf64_rela>())).r_addend as *const _ as usize },
        16usize,
        concat!(
            "Offset of field: ",
            stringify!(elf64_rela),
            "::",
            stringify!(r_addend)
        )
    );
}
pub type Elf64_Rela = elf64_rela;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct elf32_sym {
    pub st_name: Elf32_Word,
    pub st_value: Elf32_Addr,
    pub st_size: Elf32_Word,
    pub st_info: ::std::os::raw::c_uchar,
    pub st_other: ::std::os::raw::c_uchar,
    pub st_shndx: Elf32_Half,
}
#[test]
fn bindgen_test_layout_elf32_sym() {
    assert_eq!(
        ::std::mem::size_of::<elf32_sym>(),
        16usize,
        concat!("Size of: ", stringify!(elf32_sym))
    );
    assert_eq!(
        ::std::mem::align_of::<elf32_sym>(),
        4usize,
        concat!("Alignment of ", stringify!(elf32_sym))
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<elf32_sym>())).st_name as *const _ as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(elf32_sym),
            "::",
            stringify!(st_name)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<elf32_sym>())).st_value as *const _ as usize },
        4usize,
        concat!(
            "Offset of field: ",
            stringify!(elf32_sym),
            "::",
            stringify!(st_value)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<elf32_sym>())).st_size as *const _ as usize },
        8usize,
        concat!(
            "Offset of field: ",
            stringify!(elf32_sym),
            "::",
            stringify!(st_size)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<elf32_sym>())).st_info as *const _ as usize },
        12usize,
        concat!(
            "Offset of field: ",
            stringify!(elf32_sym),
            "::",
            stringify!(st_info)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<elf32_sym>())).st_other as *const _ as usize },
        13usize,
        concat!(
            "Offset of field: ",
            stringify!(elf32_sym),
            "::",
            stringify!(st_other)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<elf32_sym>())).st_shndx as *const _ as usize },
        14usize,
        concat!(
            "Offset of field: ",
            stringify!(elf32_sym),
            "::",
            stringify!(st_shndx)
        )
    );
}
pub type Elf32_Sym = elf32_sym;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct elf64_sym {
    pub st_name: Elf64_Word,
    pub st_info: ::std::os::raw::c_uchar,
    pub st_other: ::std::os::raw::c_uchar,
    pub st_shndx: Elf64_Half,
    pub st_value: Elf64_Addr,
    pub st_size: Elf64_Xword,
}
#[test]
fn bindgen_test_layout_elf64_sym() {
    assert_eq!(
        ::std::mem::size_of::<elf64_sym>(),
        24usize,
        concat!("Size of: ", stringify!(elf64_sym))
    );
    assert_eq!(
        ::std::mem::align_of::<elf64_sym>(),
        8usize,
        concat!("Alignment of ", stringify!(elf64_sym))
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<elf64_sym>())).st_name as *const _ as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(elf64_sym),
            "::",
            stringify!(st_name)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<elf64_sym>())).st_info as *const _ as usize },
        4usize,
        concat!(
            "Offset of field: ",
            stringify!(elf64_sym),
            "::",
            stringify!(st_info)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<elf64_sym>())).st_other as *const _ as usize },
        5usize,
        concat!(
            "Offset of field: ",
            stringify!(elf64_sym),
            "::",
            stringify!(st_other)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<elf64_sym>())).st_shndx as *const _ as usize },
        6usize,
        concat!(
            "Offset of field: ",
            stringify!(elf64_sym),
            "::",
            stringify!(st_shndx)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<elf64_sym>())).st_value as *const _ as usize },
        8usize,
        concat!(
            "Offset of field: ",
            stringify!(elf64_sym),
            "::",
            stringify!(st_value)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<elf64_sym>())).st_size as *const _ as usize },
        16usize,
        concat!(
            "Offset of field: ",
            stringify!(elf64_sym),
            "::",
            stringify!(st_size)
        )
    );
}
pub type Elf64_Sym = elf64_sym;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct elf32_hdr {
    pub e_ident: [::std::os::raw::c_uchar; 16usize],
    pub e_type: Elf32_Half,
    pub e_machine: Elf32_Half,
    pub e_version: Elf32_Word,
    pub e_entry: Elf32_Addr,
    pub e_phoff: Elf32_Off,
    pub e_shoff: Elf32_Off,
    pub e_flags: Elf32_Word,
    pub e_ehsize: Elf32_Half,
    pub e_phentsize: Elf32_Half,
    pub e_phnum: Elf32_Half,
    pub e_shentsize: Elf32_Half,
    pub e_shnum: Elf32_Half,
    pub e_shstrndx: Elf32_Half,
}
#[test]
fn bindgen_test_layout_elf32_hdr() {
    assert_eq!(
        ::std::mem::size_of::<elf32_hdr>(),
        52usize,
        concat!("Size of: ", stringify!(elf32_hdr))
    );
    assert_eq!(
        ::std::mem::align_of::<elf32_hdr>(),
        4usize,
        concat!("Alignment of ", stringify!(elf32_hdr))
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<elf32_hdr>())).e_ident as *const _ as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(elf32_hdr),
            "::",
            stringify!(e_ident)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<elf32_hdr>())).e_type as *const _ as usize },
        16usize,
        concat!(
            "Offset of field: ",
            stringify!(elf32_hdr),
            "::",
            stringify!(e_type)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<elf32_hdr>())).e_machine as *const _ as usize },
        18usize,
        concat!(
            "Offset of field: ",
            stringify!(elf32_hdr),
            "::",
            stringify!(e_machine)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<elf32_hdr>())).e_version as *const _ as usize },
        20usize,
        concat!(
            "Offset of field: ",
            stringify!(elf32_hdr),
            "::",
            stringify!(e_version)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<elf32_hdr>())).e_entry as *const _ as usize },
        24usize,
        concat!(
            "Offset of field: ",
            stringify!(elf32_hdr),
            "::",
            stringify!(e_entry)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<elf32_hdr>())).e_phoff as *const _ as usize },
        28usize,
        concat!(
            "Offset of field: ",
            stringify!(elf32_hdr),
            "::",
            stringify!(e_phoff)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<elf32_hdr>())).e_shoff as *const _ as usize },
        32usize,
        concat!(
            "Offset of field: ",
            stringify!(elf32_hdr),
            "::",
            stringify!(e_shoff)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<elf32_hdr>())).e_flags as *const _ as usize },
        36usize,
        concat!(
            "Offset of field: ",
            stringify!(elf32_hdr),
            "::",
            stringify!(e_flags)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<elf32_hdr>())).e_ehsize as *const _ as usize },
        40usize,
        concat!(
            "Offset of field: ",
            stringify!(elf32_hdr),
            "::",
            stringify!(e_ehsize)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<elf32_hdr>())).e_phentsize as *const _ as usize },
        42usize,
        concat!(
            "Offset of field: ",
            stringify!(elf32_hdr),
            "::",
            stringify!(e_phentsize)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<elf32_hdr>())).e_phnum as *const _ as usize },
        44usize,
        concat!(
            "Offset of field: ",
            stringify!(elf32_hdr),
            "::",
            stringify!(e_phnum)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<elf32_hdr>())).e_shentsize as *const _ as usize },
        46usize,
        concat!(
            "Offset of field: ",
            stringify!(elf32_hdr),
            "::",
            stringify!(e_shentsize)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<elf32_hdr>())).e_shnum as *const _ as usize },
        48usize,
        concat!(
            "Offset of field: ",
            stringify!(elf32_hdr),
            "::",
            stringify!(e_shnum)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<elf32_hdr>())).e_shstrndx as *const _ as usize },
        50usize,
        concat!(
            "Offset of field: ",
            stringify!(elf32_hdr),
            "::",
            stringify!(e_shstrndx)
        )
    );
}
pub type Elf32_Ehdr = elf32_hdr;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct elf64_hdr {
    pub e_ident: [::std::os::raw::c_uchar; 16usize],
    pub e_type: Elf64_Half,
    pub e_machine: Elf64_Half,
    pub e_version: Elf64_Word,
    pub e_entry: Elf64_Addr,
    pub e_phoff: Elf64_Off,
    pub e_shoff: Elf64_Off,
    pub e_flags: Elf64_Word,
    pub e_ehsize: Elf64_Half,
    pub e_phentsize: Elf64_Half,
    pub e_phnum: Elf64_Half,
    pub e_shentsize: Elf64_Half,
    pub e_shnum: Elf64_Half,
    pub e_shstrndx: Elf64_Half,
}
#[test]
fn bindgen_test_layout_elf64_hdr() {
    assert_eq!(
        ::std::mem::size_of::<elf64_hdr>(),
        64usize,
        concat!("Size of: ", stringify!(elf64_hdr))
    );
    assert_eq!(
        ::std::mem::align_of::<elf64_hdr>(),
        8usize,
        concat!("Alignment of ", stringify!(elf64_hdr))
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<elf64_hdr>())).e_ident as *const _ as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(elf64_hdr),
            "::",
            stringify!(e_ident)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<elf64_hdr>())).e_type as *const _ as usize },
        16usize,
        concat!(
            "Offset of field: ",
            stringify!(elf64_hdr),
            "::",
            stringify!(e_type)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<elf64_hdr>())).e_machine as *const _ as usize },
        18usize,
        concat!(
            "Offset of field: ",
            stringify!(elf64_hdr),
            "::",
            stringify!(e_machine)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<elf64_hdr>())).e_version as *const _ as usize },
        20usize,
        concat!(
            "Offset of field: ",
            stringify!(elf64_hdr),
            "::",
            stringify!(e_version)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<elf64_hdr>())).e_entry as *const _ as usize },
        24usize,
        concat!(
            "Offset of field: ",
            stringify!(elf64_hdr),
            "::",
            stringify!(e_entry)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<elf64_hdr>())).e_phoff as *const _ as usize },
        32usize,
        concat!(
            "Offset of field: ",
            stringify!(elf64_hdr),
            "::",
            stringify!(e_phoff)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<elf64_hdr>())).e_shoff as *const _ as usize },
        40usize,
        concat!(
            "Offset of field: ",
            stringify!(elf64_hdr),
            "::",
            stringify!(e_shoff)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<elf64_hdr>())).e_flags as *const _ as usize },
        48usize,
        concat!(
            "Offset of field: ",
            stringify!(elf64_hdr),
            "::",
            stringify!(e_flags)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<elf64_hdr>())).e_ehsize as *const _ as usize },
        52usize,
        concat!(
            "Offset of field: ",
            stringify!(elf64_hdr),
            "::",
            stringify!(e_ehsize)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<elf64_hdr>())).e_phentsize as *const _ as usize },
        54usize,
        concat!(
            "Offset of field: ",
            stringify!(elf64_hdr),
            "::",
            stringify!(e_phentsize)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<elf64_hdr>())).e_phnum as *const _ as usize },
        56usize,
        concat!(
            "Offset of field: ",
            stringify!(elf64_hdr),
            "::",
            stringify!(e_phnum)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<elf64_hdr>())).e_shentsize as *const _ as usize },
        58usize,
        concat!(
            "Offset of field: ",
            stringify!(elf64_hdr),
            "::",
            stringify!(e_shentsize)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<elf64_hdr>())).e_shnum as *const _ as usize },
        60usize,
        concat!(
            "Offset of field: ",
            stringify!(elf64_hdr),
            "::",
            stringify!(e_shnum)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<elf64_hdr>())).e_shstrndx as *const _ as usize },
        62usize,
        concat!(
            "Offset of field: ",
            stringify!(elf64_hdr),
            "::",
            stringify!(e_shstrndx)
        )
    );
}
pub type Elf64_Ehdr = elf64_hdr;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct elf32_phdr {
    pub p_type: Elf32_Word,
    pub p_offset: Elf32_Off,
    pub p_vaddr: Elf32_Addr,
    pub p_paddr: Elf32_Addr,
    pub p_filesz: Elf32_Word,
    pub p_memsz: Elf32_Word,
    pub p_flags: Elf32_Word,
    pub p_align: Elf32_Word,
}
#[test]
fn bindgen_test_layout_elf32_phdr() {
    assert_eq!(
        ::std::mem::size_of::<elf32_phdr>(),
        32usize,
        concat!("Size of: ", stringify!(elf32_phdr))
    );
    assert_eq!(
        ::std::mem::align_of::<elf32_phdr>(),
        4usize,
        concat!("Alignment of ", stringify!(elf32_phdr))
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<elf32_phdr>())).p_type as *const _ as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(elf32_phdr),
            "::",
            stringify!(p_type)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<elf32_phdr>())).p_offset as *const _ as usize },
        4usize,
        concat!(
            "Offset of field: ",
            stringify!(elf32_phdr),
            "::",
            stringify!(p_offset)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<elf32_phdr>())).p_vaddr as *const _ as usize },
        8usize,
        concat!(
            "Offset of field: ",
            stringify!(elf32_phdr),
            "::",
            stringify!(p_vaddr)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<elf32_phdr>())).p_paddr as *const _ as usize },
        12usize,
        concat!(
            "Offset of field: ",
            stringify!(elf32_phdr),
            "::",
            stringify!(p_paddr)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<elf32_phdr>())).p_filesz as *const _ as usize },
        16usize,
        concat!(
            "Offset of field: ",
            stringify!(elf32_phdr),
            "::",
            stringify!(p_filesz)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<elf32_phdr>())).p_memsz as *const _ as usize },
        20usize,
        concat!(
            "Offset of field: ",
            stringify!(elf32_phdr),
            "::",
            stringify!(p_memsz)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<elf32_phdr>())).p_flags as *const _ as usize },
        24usize,
        concat!(
            "Offset of field: ",
            stringify!(elf32_phdr),
            "::",
            stringify!(p_flags)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<elf32_phdr>())).p_align as *const _ as usize },
        28usize,
        concat!(
            "Offset of field: ",
            stringify!(elf32_phdr),
            "::",
            stringify!(p_align)
        )
    );
}
pub type Elf32_Phdr = elf32_phdr;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct elf64_phdr {
    pub p_type: Elf64_Word,
    pub p_flags: Elf64_Word,
    pub p_offset: Elf64_Off,
    pub p_vaddr: Elf64_Addr,
    pub p_paddr: Elf64_Addr,
    pub p_filesz: Elf64_Xword,
    pub p_memsz: Elf64_Xword,
    pub p_align: Elf64_Xword,
}
#[test]
fn bindgen_test_layout_elf64_phdr() {
    assert_eq!(
        ::std::mem::size_of::<elf64_phdr>(),
        56usize,
        concat!("Size of: ", stringify!(elf64_phdr))
    );
    assert_eq!(
        ::std::mem::align_of::<elf64_phdr>(),
        8usize,
        concat!("Alignment of ", stringify!(elf64_phdr))
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<elf64_phdr>())).p_type as *const _ as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(elf64_phdr),
            "::",
            stringify!(p_type)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<elf64_phdr>())).p_flags as *const _ as usize },
        4usize,
        concat!(
            "Offset of field: ",
            stringify!(elf64_phdr),
            "::",
            stringify!(p_flags)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<elf64_phdr>())).p_offset as *const _ as usize },
        8usize,
        concat!(
            "Offset of field: ",
            stringify!(elf64_phdr),
            "::",
            stringify!(p_offset)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<elf64_phdr>())).p_vaddr as *const _ as usize },
        16usize,
        concat!(
            "Offset of field: ",
            stringify!(elf64_phdr),
            "::",
            stringify!(p_vaddr)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<elf64_phdr>())).p_paddr as *const _ as usize },
        24usize,
        concat!(
            "Offset of field: ",
            stringify!(elf64_phdr),
            "::",
            stringify!(p_paddr)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<elf64_phdr>())).p_filesz as *const _ as usize },
        32usize,
        concat!(
            "Offset of field: ",
            stringify!(elf64_phdr),
            "::",
            stringify!(p_filesz)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<elf64_phdr>())).p_memsz as *const _ as usize },
        40usize,
        concat!(
            "Offset of field: ",
            stringify!(elf64_phdr),
            "::",
            stringify!(p_memsz)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<elf64_phdr>())).p_align as *const _ as usize },
        48usize,
        concat!(
            "Offset of field: ",
            stringify!(elf64_phdr),
            "::",
            stringify!(p_align)
        )
    );
}
pub type Elf64_Phdr = elf64_phdr;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct elf32_shdr {
    pub sh_name: Elf32_Word,
    pub sh_type: Elf32_Word,
    pub sh_flags: Elf32_Word,
    pub sh_addr: Elf32_Addr,
    pub sh_offset: Elf32_Off,
    pub sh_size: Elf32_Word,
    pub sh_link: Elf32_Word,
    pub sh_info: Elf32_Word,
    pub sh_addralign: Elf32_Word,
    pub sh_entsize: Elf32_Word,
}
#[test]
fn bindgen_test_layout_elf32_shdr() {
    assert_eq!(
        ::std::mem::size_of::<elf32_shdr>(),
        40usize,
        concat!("Size of: ", stringify!(elf32_shdr))
    );
    assert_eq!(
        ::std::mem::align_of::<elf32_shdr>(),
        4usize,
        concat!("Alignment of ", stringify!(elf32_shdr))
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<elf32_shdr>())).sh_name as *const _ as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(elf32_shdr),
            "::",
            stringify!(sh_name)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<elf32_shdr>())).sh_type as *const _ as usize },
        4usize,
        concat!(
            "Offset of field: ",
            stringify!(elf32_shdr),
            "::",
            stringify!(sh_type)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<elf32_shdr>())).sh_flags as *const _ as usize },
        8usize,
        concat!(
            "Offset of field: ",
            stringify!(elf32_shdr),
            "::",
            stringify!(sh_flags)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<elf32_shdr>())).sh_addr as *const _ as usize },
        12usize,
        concat!(
            "Offset of field: ",
            stringify!(elf32_shdr),
            "::",
            stringify!(sh_addr)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<elf32_shdr>())).sh_offset as *const _ as usize },
        16usize,
        concat!(
            "Offset of field: ",
            stringify!(elf32_shdr),
            "::",
            stringify!(sh_offset)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<elf32_shdr>())).sh_size as *const _ as usize },
        20usize,
        concat!(
            "Offset of field: ",
            stringify!(elf32_shdr),
            "::",
            stringify!(sh_size)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<elf32_shdr>())).sh_link as *const _ as usize },
        24usize,
        concat!(
            "Offset of field: ",
            stringify!(elf32_shdr),
            "::",
            stringify!(sh_link)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<elf32_shdr>())).sh_info as *const _ as usize },
        28usize,
        concat!(
            "Offset of field: ",
            stringify!(elf32_shdr),
            "::",
            stringify!(sh_info)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<elf32_shdr>())).sh_addralign as *const _ as usize },
        32usize,
        concat!(
            "Offset of field: ",
            stringify!(elf32_shdr),
            "::",
            stringify!(sh_addralign)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<elf32_shdr>())).sh_entsize as *const _ as usize },
        36usize,
        concat!(
            "Offset of field: ",
            stringify!(elf32_shdr),
            "::",
            stringify!(sh_entsize)
        )
    );
}
pub type Elf32_Shdr = elf32_shdr;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct elf64_shdr {
    pub sh_name: Elf64_Word,
    pub sh_type: Elf64_Word,
    pub sh_flags: Elf64_Xword,
    pub sh_addr: Elf64_Addr,
    pub sh_offset: Elf64_Off,
    pub sh_size: Elf64_Xword,
    pub sh_link: Elf64_Word,
    pub sh_info: Elf64_Word,
    pub sh_addralign: Elf64_Xword,
    pub sh_entsize: Elf64_Xword,
}
#[test]
fn bindgen_test_layout_elf64_shdr() {
    assert_eq!(
        ::std::mem::size_of::<elf64_shdr>(),
        64usize,
        concat!("Size of: ", stringify!(elf64_shdr))
    );
    assert_eq!(
        ::std::mem::align_of::<elf64_shdr>(),
        8usize,
        concat!("Alignment of ", stringify!(elf64_shdr))
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<elf64_shdr>())).sh_name as *const _ as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(elf64_shdr),
            "::",
            stringify!(sh_name)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<elf64_shdr>())).sh_type as *const _ as usize },
        4usize,
        concat!(
            "Offset of field: ",
            stringify!(elf64_shdr),
            "::",
            stringify!(sh_type)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<elf64_shdr>())).sh_flags as *const _ as usize },
        8usize,
        concat!(
            "Offset of field: ",
            stringify!(elf64_shdr),
            "::",
            stringify!(sh_flags)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<elf64_shdr>())).sh_addr as *const _ as usize },
        16usize,
        concat!(
            "Offset of field: ",
            stringify!(elf64_shdr),
            "::",
            stringify!(sh_addr)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<elf64_shdr>())).sh_offset as *const _ as usize },
        24usize,
        concat!(
            "Offset of field: ",
            stringify!(elf64_shdr),
            "::",
            stringify!(sh_offset)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<elf64_shdr>())).sh_size as *const _ as usize },
        32usize,
        concat!(
            "Offset of field: ",
            stringify!(elf64_shdr),
            "::",
            stringify!(sh_size)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<elf64_shdr>())).sh_link as *const _ as usize },
        40usize,
        concat!(
            "Offset of field: ",
            stringify!(elf64_shdr),
            "::",
            stringify!(sh_link)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<elf64_shdr>())).sh_info as *const _ as usize },
        44usize,
        concat!(
            "Offset of field: ",
            stringify!(elf64_shdr),
            "::",
            stringify!(sh_info)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<elf64_shdr>())).sh_addralign as *const _ as usize },
        48usize,
        concat!(
            "Offset of field: ",
            stringify!(elf64_shdr),
            "::",
            stringify!(sh_addralign)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<elf64_shdr>())).sh_entsize as *const _ as usize },
        56usize,
        concat!(
            "Offset of field: ",
            stringify!(elf64_shdr),
            "::",
            stringify!(sh_entsize)
        )
    );
}
pub type Elf64_Shdr = elf64_shdr;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct elf32_note {
    pub n_namesz: Elf32_Word,
    pub n_descsz: Elf32_Word,
    pub n_type: Elf32_Word,
}
#[test]
fn bindgen_test_layout_elf32_note() {
    assert_eq!(
        ::std::mem::size_of::<elf32_note>(),
        12usize,
        concat!("Size of: ", stringify!(elf32_note))
    );
    assert_eq!(
        ::std::mem::align_of::<elf32_note>(),
        4usize,
        concat!("Alignment of ", stringify!(elf32_note))
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<elf32_note>())).n_namesz as *const _ as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(elf32_note),
            "::",
            stringify!(n_namesz)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<elf32_note>())).n_descsz as *const _ as usize },
        4usize,
        concat!(
            "Offset of field: ",
            stringify!(elf32_note),
            "::",
            stringify!(n_descsz)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<elf32_note>())).n_type as *const _ as usize },
        8usize,
        concat!(
            "Offset of field: ",
            stringify!(elf32_note),
            "::",
            stringify!(n_type)
        )
    );
}
pub type Elf32_Nhdr = elf32_note;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct elf64_note {
    pub n_namesz: Elf64_Word,
    pub n_descsz: Elf64_Word,
    pub n_type: Elf64_Word,
}
#[test]
fn bindgen_test_layout_elf64_note() {
    assert_eq!(
        ::std::mem::size_of::<elf64_note>(),
        12usize,
        concat!("Size of: ", stringify!(elf64_note))
    );
    assert_eq!(
        ::std::mem::align_of::<elf64_note>(),
        4usize,
        concat!("Alignment of ", stringify!(elf64_note))
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<elf64_note>())).n_namesz as *const _ as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(elf64_note),
            "::",
            stringify!(n_namesz)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<elf64_note>())).n_descsz as *const _ as usize },
        4usize,
        concat!(
            "Offset of field: ",
            stringify!(elf64_note),
            "::",
            stringify!(n_descsz)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<elf64_note>())).n_type as *const _ as usize },
        8usize,
        concat!(
            "Offset of field: ",
            stringify!(elf64_note),
            "::",
            stringify!(n_type)
        )
    );
}
pub type Elf64_Nhdr = elf64_note;
